const supabaseUrl = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzdG1uYXpoZ2FmZWRyenFqa21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MzQ5MDgsImV4cCI6MjA2NTAxMDkwOH0.FA2fKqFxzwmrys0i3VG2WPnvNY9XhPISxMsy_S3uJHg';
const supabaseKey = 'https://zstmnazhgafedrzqjkmn.supabase.co';
window.supabase = supabase.createClient(supabaseUrl, supabaseKey);
